W5D1/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums
  resources :tracks do
    resources :notes, only: [:index]
  end
  resources :notes, only: [:new, :create, :destroy, :show]
end

W5D1/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy
end

W5D1/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W5D1/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/MusicApp/app/views/bands/edit.html.erb
<form action="<%= band_url %>" method="post">
  <input type="hidden" name="_method", value="PATCH">

  <label for="name">Name: </label>
  <input id="name" type="text" name="band[name]" value="<%= @band.name %>">
  <br>
  <input type="submit" value="submit">

</form>

W5D1/MusicApp/app/views/bands/index.html.erb
<div class="band-indx">
  <% @bands.each do |band| %>
    <ul>
      <li>
        <%= link_to band.name, band_path(band) %>
      </li> <br>
    </ul>
  <% end %>
</div>

W5D1/MusicApp/app/views/bands/new.html.erb
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <ul>
      <%= error %>
    </ul>
    <% end %>
<% end %>

<form action="<%= bands_url %>" method="post">
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="name">Name: </label>
  <input id="name" type="text" name="band[name]">
  <br>
  <input type="submit" value="submit">

</form>

W5D1/MusicApp/app/views/bands/show.html.erb
<a><%= link_to "home", bands_path %></a>
<div class="actual-name">
  <a><%= @band.name %></a>
</div>
<% @band.albums.each do |album| %>
  <%= album.title %><br>
<% end %>
<ul class="options-band">
  <li><%= link_to "update", edit_band_path(@band) %></li>
  <li><%= link_to "delete", band_url(@band), method: :destroy %></li>
</ul>