W5D1/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums
  resources :tracks do
    resources :notes, only: [:index]
  end
  resources :notes, only: [:new, :create, :destroy, :show]
end

W5D1/MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  band_id        :integer          not null
#  title          :string           not null
#  year           :integer          not null
#  recording_type :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, :recording_type, presence: true
  validates :recording_type, inclusion: { in: ["Studio", "Live"]}

  has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Track,
    dependent: :destroy

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band
end

W5D1/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :recording_type)
  end
end

W5D1/MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/MusicApp/app/views/albums/edit.html.erb
<form action="<%= album_url %>" method="post">
  <input type="hidden" name="_method", value="PATCH">

  <label for="Band">Band: </label>
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%=band.id%>" <%= @album.band_id == band.id ? "selected" : "" %>><%=band.name%></option>
    <% end %>
  </select>
  <br>
  <label for="title">Name: </label>
  <input id="title" type="text" name="album[title]" value="<%= @album.title %>">
  <br>
  <label for="year">Year: </label>
  <input id="year" type="number" name="album[year]" value="<%= @album.year %>">
  <br>
  <input type="radio" name="album[recording_type]" value="Studio" <%= @album.recording_type == "Studio" ? "checked" : "" %> > Studio<br>
  <input type="radio" name="album[recording_type]" value="Live" <%= @album.recording_type == "Live" ? "checked" : "" %> > Live<br>
  <br>
  <input type="submit" value="submit">

</form>

W5D1/MusicApp/app/views/albums/index.html.erb
<div class="album-indx">
  <% @albums.each do |album| %>
    <ul>
      <li>
        <%= Band.find(album.band_id).name %><br>
        <%= link_to album.title, album_path(album) %>
      </li> <br>
    </ul>
  <% end %>
</div>

W5D1/MusicApp/app/views/albums/new.html.erb
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <ul>
      <%= error %>
    </ul>
    <% end %>
<% end %>

<form action="<%= albums_url %>" method="post">
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="Band">Band: </label>
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%=band.id%>"><%=band.name%></option>
    <% end %>
  </select>
  <br>
  <label for="title">Name: </label>
  <input id="title" type="text" name="album[title]">
  <br>
  <label for="year">Year: </label>
  <input id="year" type="number" name="album[year]">
  <br>
  <input type="radio" name="album[recording_type]" value="Studio" checked> Studio<br>
  <input type="radio" name="album[recording_type]" value="Live"> Live<br>
  <br>
  <input type="submit" value="submit">
</form>

W5D1/MusicApp/app/views/albums/show.html.erb
<a><%= link_to "home", albums_path %></a>
<div class="actual-name" style="font-size: 20px;">
  <p>BAND:</p> <a><%= Band.find(@album.band_id).name %></a><br>
  <p>TITLE:</p> <a><%= @album.title %></a><br>
  <p>YEAR:</p> <a><%= @album.year %></a><br>
  <p>TYPE:</p> <a><%= @album.recording_type %></a><br>
</div>
<ul class="options-album">
  <li><%= link_to "update", edit_album_path(@album), method: :patch %></li>
  <li><%= link_to "delete", album_url(@album), method: :delete %></li>
</ul>