W5D1/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums
  resources :tracks do
    resources :notes, only: [:index]
  end
  resources :notes, only: [:new, :create, :destroy, :show]
end

W5D1/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h2>
        <div='img-logo'>
          <%= image_tag("logo.jpg", height: '120', width: '120') %>
        </div>
        <% if current_user %>
          <form class='button_to' method='post' action='/session' data-remote='true'>
             <input name='_method' value='delete' type='hidden' />
             <input value='Log Out' type='submit' data-disable-with='loading...' data-confirm='Are you sure?' />
             <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
          </form>
        <% end %>
      </h2>
      <ul class="layout-list">
        <a><%= link_to "Check Out Bands", bands_path %></a>
        <a><%= link_to "Check Out Albums", albums_path %></a>
        <a><%= link_to "Check Out Tracks", tracks_path %></a>
      <ul>
    </header>
    <%= yield %>
  </body>

</html>